#!/bin/bash
echo "memcmp for ${1}"

nv-nsight-cu-cli --metrics l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,l1tex__t_requests_pipe_lsu_mem_global_op_ld.sum $1 ../mnist/mnist_encoded/encoded_train_ae.npy
